export const GET_SELECTED_LOCATION = 'GET_SELECTED_LOCATION';
export const SET_WEATHER = 'SET_WEATHER';
export const SET_HIGHLIGHTED_DAY_ID = 'SET_HIGHLIGHTED_DAY_ID';
export const CHANGE_WEATHER_VIEW = 'CHANGE_WEATHER_VIEW';
export const FETCH_TEMPERATURE_FORCAST_DATA = 'FETCH_TEMPERATURE_FORCAST_DATA';
